experiment:
  exp_name: test
  save_dir: logs

data:
  image_path: datas/train/images
  label_path: 
  - datas/train/labels_0
  - datas/train/labels_1
  stn_test_path: datas/val/images
  num_workers: 0
  pin_memory: true
  stn_correction: true

predict:
  model_path: pretrain/meter/textgraph_convnext_tiny_100_release.pth
  stn_model_path: pretrain/stn/ep35_loss0.0551.pth
  yolo_model_path: pretrain/yolo/best.pt
  use_yolo: true
  use_stn: true
  yolo_imgsz: 640
  yolo_conf: 0.6
  yolo_iou: 0.3
  yolo_max_det: 160
  yolo_device: auto
  yolo_half: null

model:
  net: convnext_tiny
  use_multimodal: true
  test_size: [512, 1024]
  means: [0.485, 0.456, 0.406]
  stds: [0.229, 0.224, 0.225]

training:
  device: cuda:0
  seed: 114514
  max_epoch: 100
  start_epoch: 0
  batch_size: 2
  lr: 0.0001
  lr_adjust: cosine
  optim: AdamW
  weight_decay: 0.01
  eta_min: 0.000001
  cosine_t_max: 101
  gamma: 0.1
  momentum: 0.9
  display_freq: 10

stn_training:
  device: cuda:0
  seed: 114514
  epochs: 100
  batch_size: 16
  lr: 0.0001
  lr_min: 0.000001
  step: 100
  disable_homography: false
  disable_artefacts: false
  disable_arguments: false
